name: dart_procr
description: An audio album builder.
# version: 1.0.0
# homepage: https://www.example.com
# author: My Name <email@example.com>

environment:
  sdk: '>=2.10.0 <3.0.0'

dependencies:
  path: ^1.8.0
  args: ^2.3.0

dev_dependencies:
  test: ^1.18.2
