name: dart_procr
description: An audio album builder.
# version: 1.0.0
# homepage: https://www.example.com
# author: My Name <email@example.com>

environment:
  sdk: '>=2.0.0-dev.55.0 <2.0.0'

dependencies:
  path: ^1.6.1
  args: ^1.4.3

dev_dependencies:
  test: ^0.12.30
